title: "Keyi Fan"
email: keyifan@hks.harvard.edu
description: "Academic website of Keyi Fan"
baseurl: ""
url: "https://key1fan.github.io"
theme: null
plugins:
  - jekyll-feed
  - jekyll-include-cache

markdown: kramdown
highlighter: rouge

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

repository: "Key1Fan/keyifan.github.io"
